### ISSUE TITLE
El Capitan

### ISSUE THREAD

**Issue by titaniumjones** [mono/website#150]
Don't know if it is deliberate, but there is no link to the 4.0.4.4 for El Capitan version mentioned at the top of the Mac Download page.

The second link on the page takes you to downloading 4.2.0

**Comment by akoeplinger** [comment]
Looks like the link wasn't updated in https://github.com/mono/website/commit/2fa39f6c35a05938a4e2745bd36905086fb5ee43, fixed it with https://github.com/mono/website/commit/c002707a2f5c9955b3c8877cddac24c2401aa20a.

I'm actually not sure if the separate El Capitan preview (which is really just the upcoming Mono 4.2 release) is still required. @alexischr do you know if we still need it?

**Comment by Iritscen** [comment]
If I may interject my own opinion to that question -- I'm not familiar with Mono 4.2 versus 4.0 as far as which one should be getting offered on the Mac download page, but I would just like to point out that many El Capitan users are probably downloading the El Capitan preview at the second link, since the language on the page tends to lead them there ("Oh, the latest version is '4.0.4 SR 4 El Capitan hotfix'? I see, here's the 'Mono Preview package for El Capitan'." _clicks second link_)  It's not apparent that the "4.0.4" is referring to the first link unless one inspects the download URLs before clicking.

The problem with this is that, even though the second package contains a later Mono version, the package was produced before the fix was made to the Installer postinstall script, and it still attempts to install the Mono soft-links to /usr/bin/, which 10.11's SIP feature always blocks.  So the page's wording and the way the links are provided are probably causing a number of people to pick the package which is less likely to work for them (unless they are using a Mono-based app that calls Mono at /Library/Frameworks/Mono.framework, in which case no harm done).

**Comment by titaniumjones** [comment]
I must admit, I was confused. The only reason I figured it out, was that the version 4.2 didn't work and the 4.0.4 didn't work which is when I realised that I had to modify the URL to get the "Hot Fix" I found a version (2.10.......) That DID work on El Capitan and with the Application I was running.

**Comment by akoeplinger** [comment]
Hey guys, thanks for the additional heads up. The link to the El Capitan preview was pointing to an earlier Mono 4.2 preview, I've corrected the link to the latest preview which includes the El Capitan fixes, please try them out. Thanks :)

**Comment by Iritscen** [comment]
Thanks. I can confirm that the 4.2.1 .pkg does have the fix for 10.11's SIP (i.e., moving Mono to /usr/local/bin/).  Once bug #33912 is fixed, I'm sure the next release after that will install properly on my newer Mac.
