### ISSUE TITLE
libgdiplus DllNotFoundException on Xamarin Android project

### ISSUE THREAD

**Issue by yk-e** [mono/website#340]
I am using Windows 10 and installed Mono version 5.4.1 also I have installed Gtk# for .Net 2.12.45. I use System.Drawing.dll on my Xamarin project. While debugging the my sample application on Android emulator, libgdiplus exception is thrown. Should Mono include libgdiplus.dll on it? 
I have read this page;
http://www.mono-project.com/docs/advanced/pinvoke/dllnotfoundexception/ 
but the solution doesn't work for Windows.
Is there missing packages about my Mono installation related to libgdiplus?

**Comment by akoeplinger** [comment]
This repository is for issues related to the Mono website (http://www.mono-project.com).

I'd suggest you file your issue on the Xamarin.Android repository: https://github.com/xamarin/xamarin-android/issues

In general there seems to be a confusion, the Mono installed on the system isn't used in a Xamarin.Android application since it embeds it's own special version of Mono.
